### PR TITLE
Fix no response failure

### PR DESCRIPTION
**Pull request by elenate**
Sometimes it can happen that API will respond with empty body,
    and you will not get response and status code,
    which is bad, but you get internal Fetch error,
    but it also dousnt help and its only source of confusion.
    So by adding this, catch we can gracefully handle invalid API response

### CODE REVIEW

**Comment by dimchez** [comment]
I would say that if body is empty and response status code is 2xx then promise should not be rejected. Is the response code 204 when body is empty or is it 200?

**Comment by iamstarkov** [comment]
> Is the response code 204 when body is empty or is it 200?

no, response code is 403

**Comment by dimchez** [comment]
Ok, then it makes sense.

**Comment by iamstarkov** [comment]
the only reason why promise is rejected its because for whatever reason fetch cant handle response and explodes, and rejecting the promise makes sense because its not normal flow

**Pull request merged**
